### ISSUE TITLE
Знайти місце проведення виховного заходу

### ISSUE THREAD

**Issue by Galiv** [Galiv/who-is-on-top#1]
Нам потрібно поговорити з класним керівником 10-А де саме ми б могли провести виховний захід

**Comment by Galiv** [comment]
Чи має хтось номер класного керівника - Оксани Степанівни?

**Comment by irynaa-semchuk** [comment]
Так, маю зараз надішлю

**Comment by irynaa-semchuk** [comment]
0987652345

**Comment by Galiv** [comment]
Дуже дякую, йду дзвонити:)

**Comment by Galiv** [comment]
Оксана Степанівна погодилася, на те, що б ми провели наш захід в 308 аудиторії

**Comment by irynaa-semchuk** [comment]
Ууура, ми знайшли місце)
