### ISSUE TITLE
Придумати 2 раунд

### ISSUE THREAD

**Issue by irynaa-semchuk** [Galiv/who-is-on-top#10]
Потрібно придумати завдання для раунду №2. «ЗБЕРИ ЛІТЕРИ»

**Comment by irynaa-semchuk** [comment]
Давайте перше завдання для хлопців і дівчат буде  за 60 секунд вибудувати максимально велику кількість слів із 
чотирьох літер.

**Comment by nsavchuk41** [comment]
хороша ідея

**Comment by nsavchuk41** [comment]
і за це завдання можна буде отримати 1000 бітів

**Comment by irynaa-semchuk** [comment]
Так, можна

**Comment by irynaa-semchuk** [comment]
Завдання для дівчат: (ХД, АУ, МС, ОА)

**Comment by irynaa-semchuk** [comment]
Вона ніколи не помиляється коли приземляється на монітор, 
цокотуха-… (муха)

**Comment by nsavchuk41** [comment]
Ще можна щось таке 
Коли не впорядковувати інформацію на жорсткому диску, тоді там виникає безлад, інша назва …

**Comment by irynaa-semchuk** [comment]
Ок, тоді подібні питання запишемо у файл

**Comment by irynaa-semchuk** [comment]
Завдання для хлопців (ВЛ, ИІ, ПД, ОА):

**Comment by irynaa-semchuk** [comment]
Інформатика розвивається і крокує у незвідані … (далі)

**Comment by irynaa-semchuk** [comment]
Ще потрібне бонусне завдання? Є ідеї?

**Comment by nsavchuk41** [comment]
Скільки відсотків користувачів використовують найпопулярніший браузер у світі Google Chrome ?

**Comment by irynaa-semchuk** [comment]
Що будем робити з літерами для команд?

**Comment by nsavchuk41** [comment]
Можна надрукувати літери і роздати учням.
Кожний матиме по 2  літери

**Comment by irynaa-semchuk** [comment]
Супер, мені подобається!
