### ISSUE TITLE
Створення команди дівчат

### ISSUE THREAD

**Issue by nsavchuk41** [Galiv/who-is-on-top#11]
Потрібно обрати серед дівчат 10-А чотирьох учасників шоу.

**Comment by nsavchuk41** [comment]
Я отримала список дівчат.

1. Кравець Марта
2. Остапишин Зоряна
3. Жолудєва Наталія
4. Ризванюк Тетяна
5. Матюшко Елеонора
6. Герега Ірина
7. Любченко Анжеліка
8. Магдяк Андріана
9. Левкін Наталія
10. Кузьменко Ірина

**Comment by nsavchuk41** [comment]
Думаю потрібно аналогічно взяти чотирьох дівчат, які найкраще написали контрольну.
що думаєте @Galiv , @irynaa-semchuk??

**Comment by irynaa-semchuk** [comment]
Так, це буде добре

**Comment by nsavchuk41** [comment]
Найкраще написали:

1. Кузьменко Ірина
2. Жолудєва Наталія
3. Остапишин Зоряна
4. Герега Ірина
