### ISSUE TITLE
Допомогти команді дівчат обрати капітана та елементи гардеробу.

### ISSUE THREAD

**Issue by nsavchuk41** [Galiv/who-is-on-top#12]
Допомогти команді  обрати капітана та елементи гардеробу, що будуть вказувати на приналежність до команди.

**Comment by nsavchuk41** [comment]
Найкраще тест з інформатики написала Герега Ірина , тому пропоную її обратьи капітаном

**Comment by nsavchuk41** [comment]
А елементом гардеробу пропоную обрати рожеві футболшки?
https://futbolkashop.com.ua/product/krasnaya-odnotonnaya-futbolka/

**Comment by irynaa-semchuk** [comment]
Так, хай буде капітаном це хороший варіант)

**Comment by irynaa-semchuk** [comment]
У хлопців будуть синіх футболках, тому думаю що дійсно дівчатам буде добре у рожевих)

**Comment by nsavchuk41** [comment]
Чи потрібно капітану якусь іншу футболку?

**Comment by irynaa-semchuk** [comment]
Думаю, що не потрібна

**Comment by nsavchuk41** [comment]
тоді дівчата будуть просто у рожевих)
