### ISSUE TITLE
ПІДВЕДЕННЯ ПІДСУМКІВ

### ISSUE THREAD

**Issue by nsavchuk41** [Galiv/who-is-on-top#16]
ФІНАЛ!

**Comment by nsavchuk41** [comment]
Які ідеї є призів для переможців?

**Comment by irynaa-semchuk** [comment]
Думаю, можна організувати для переможців екскурсію в IT компанії. Як тобі така ідея?

**Comment by nsavchuk41** [comment]
Ідея хороша.
А за активну участь тоді можна придумати якісь приємні подарунки(наприклад: блокнотики, ручки, коврики для мишки).
І також звісно виставити бали.

**Comment by irynaa-semchuk** [comment]
класна ідея!
