### ISSUE TITLE
Організувати обладнання

### ISSUE THREAD

**Issue by Galiv** [Galiv/who-is-on-top#3]
Комп'ютери, проектор, роздатковий матеріал.

**Comment by Galiv** [comment]
Вчитель інформатики погодився позичити ноутбуки та проектор на день заходу

**Comment by Galiv** [comment]
[https://komputers.com.ua/wp-content/uploads/2018/04/kupiti-noutbuk-bu-rovno-900x444.jpg](url)

Ось фото комп'ютерів

**Comment by Galiv** [comment]
[https://img.moyo.ua/img/news_desc/1663/166385_1573038946_0.jpg](url)

Ось проектор

**Comment by irynaa-semchuk** [comment]
Мені подобається ))
