### ISSUE TITLE
Створення команди хлопців

### ISSUE THREAD

**Issue by irynaa-semchuk** [Galiv/who-is-on-top#4]
Потрібно обрати серед хлопців 10-А чотирьох учасників шоу.

**Comment by irynaa-semchuk** [comment]
Мені Оксана Степанівна надіслала список групи, нам потрібно вирішити яких хлопчиків оберемо в команду, а які будуть вболівальниками

**Comment by irynaa-semchuk** [comment]
1. Степан Максимяк
2. Максим Петришин
3. Ярослав Шкарбан
4. Микола Яворишин
5. Олег Савчук
6. Діма Круткоський
7. Олег Садовий
8. Святослав Юрас
9. Сергій Аксимитов
10. Андрій Цук

**Comment by Galiv** [comment]
Чи є ідеї, як саме будемо обирати?

**Comment by irynaa-semchuk** [comment]
Давайте оберемо 4-ох хлопців які найкраще написали останню контрольну з інформатики

**Comment by Galiv** [comment]
@nsavchuk41 що думаєш?

**Comment by nsavchuk41** [comment]
Я підтримую)

**Comment by irynaa-semchuk** [comment]
Тоді ось список хлопців:
Ярослав Шкарбан
Діма Круткоський
Святослав Юрас
Сергій Аксимитов

**Comment by Galiv** [comment]
[https://komputers.com.ua/wp-content/uploads/2018/04/kupiti-noutbuk-bu-rovno-900x444.jpg](url)
