### ISSUE TITLE
Допомогти команді хлопців обрати капітана та елементи гардеробу.

### ISSUE THREAD

**Issue by irynaa-semchuk** [Galiv/who-is-on-top#5]
Допомогти команді хлопців обрати капітана та елементи гардеробу, що будуть вказувати на приналежність до команди і готує домашнє завдання

**Comment by irynaa-semchuk** [comment]
Пропоную обрати того, хто найкраще написав тест по інформатиці)

**Comment by irynaa-semchuk** [comment]
Сергій Аксимитов, написав найкраще

**Comment by irynaa-semchuk** [comment]
Як вам такий варіант?

**Comment by nsavchuk41** [comment]
Думаю, що це хороша ідея

**Comment by irynaa-semchuk** [comment]
Ну тоді це узгодили. Потрібно ще обрати елементи гардеробу

**Comment by irynaa-semchuk** [comment]
[https://berrytex.com.ua/futbolki/](url)
Пропоную сині футболки всім учаснинкам

**Comment by Galiv** [comment]
Мені подобається)
