### ISSUE TITLE
Знайти і створити файл з жартами.

### ISSUE THREAD

**Issue by irynaa-semchuk** [Galiv/who-is-on-top#6]
Нам потрібні жарти на випадок, якщо потрібно буде заповнити паузу.

**Comment by Galiv** [comment]
- Олю, скажи, а коли я копіюю мишкою текст, де він зберігається?
- Як де? Звичайно, у мишці!

**Comment by Galiv** [comment]
- Петро Петрович! А у моєї бабусі Клави яке повне ім'я?
- Клавдія.
- Шкода, а то я з Колькою посперечався, що Клавіатура!

**Comment by irynaa-semchuk** [comment]
А ти знаєш аварійний вихід з Windows?
- Ні.
- Висмикни шнур, видави екран

**Comment by irynaa-semchuk** [comment]
У кабінеті лікаря:
- Очі почервонілі, опухлі, скарги на різь...
- Весняний кон'юнктивіт?
- Безлімітний інтернет...

**Comment by Galiv** [comment]
- Не було печалі -
- З youtub'a накачали.
