### ISSUE TITLE
Створити завдання для Раунд 3.

### ISSUE THREAD

**Issue by Galiv** [Galiv/who-is-on-top#7]
Створити завдання для Раунд 3. «ПОКАЖИ НАЗВУ»

**Comment by irynaa-semchuk** [comment]
Давайте правильна відповідь – 1000 бітів

**Comment by nsavchuk41** [comment]
Давайте зробимо обмеження на виконання даного завдання 60с. Ок?

**Comment by Galiv** [comment]
Таак! Мені подобається ідея. Тоді нехай буде так: у навушниках один учасник команди слухає пісню, текст якої
пов’язаний із інформатикою. Потім він показує за допомогою жестів, міміки (без озвучення) своїй команді. Команда повинна за 60 секунд відгадати назву пісні або хоча б проспівати частину її слів.

**Comment by Galiv** [comment]
І бонусне питання - Найпопулярніший пошуковий сервіс Google у світі використовують ...
% користувачів?
