### ISSUE TITLE
Придумати 1 раунд

### ISSUE THREAD

**Issue by irynaa-semchuk** [Galiv/who-is-on-top#8]
Потрібно придумати завдання для раунду №1. «ЧИ ЗНАЄТЕ ВИ НАС?»

**Comment by irynaa-semchuk** [comment]
Давайте перше завдання для хлопців. Чи добре ви знаєте дівчат? Час на виконання 60 
секунд.

**Comment by Galiv** [comment]
Так, і тоді завдання у відповідь, для дівчат. Чи добре ви знаєте, дівчата, хлопців у залі?

**Comment by irynaa-semchuk** [comment]
Супер!

**Comment by irynaa-semchuk** [comment]
Хто переможе буде отрмувати 1000 бітів?

**Comment by nsavchuk41** [comment]
так

**Comment by irynaa-semchuk** [comment]
Завдання для хлопців: Який стаціонарний ПК обрали б хлопці?

**Comment by nsavchuk41** [comment]
Завдання для дівчат: Який ноутбук обрали б наші дівчата в класі?

**Comment by nsavchuk41** [comment]
Потрібно знайти якісь фото та характеристики?

**Comment by irynaa-semchuk** [comment]
Тоді перший раунд готовий)

**Comment by irynaa-semchuk** [comment]
Так, вони вже знайдені і будуть викладені у файлі на головній сторінці

**Comment by nsavchuk41** [comment]
Можливо команда яка правильно відповіла, матиме можливість отримати додаткові біти ?

**Comment by irynaa-semchuk** [comment]
так, буде мати

**Comment by irynaa-semchuk** [comment]
ми можем додати бонусне завдання

**Comment by irynaa-semchuk** [comment]
Помилитися можна на +-10%.

**Comment by irynaa-semchuk** [comment]
Наприклад таке запитання, скільки відсотків комп’ютерів у світі використовують ОС Windows 7?

**Comment by nsavchuk41** [comment]
Питання однакове для хлопців та діавчат?

**Comment by irynaa-semchuk** [comment]
Так, однакове, адже тільки одна команда переможе в раунді

**Comment by irynaa-semchuk** [comment]
Хто переможе тому і додаткове запитання

**Comment by nsavchuk41** [comment]
ок

**Comment by nsavchuk41** [comment]
а якщо буде нічия ?

**Comment by irynaa-semchuk** [comment]
то дивоглядки

**Comment by nsavchuk41** [comment]
ок.
