### ISSUE TITLE
Створити завдання для Раунд 4.

### ISSUE THREAD

**Issue by Galiv** [Galiv/who-is-on-top#9]
Створити завдання для Раунд 4. "Хто Я?"

**Comment by Galiv** [comment]
Один учасник команди виходить за імпровізовану ширму-екран.
Учасник ставить запитання до своєї команди, а ті можуть відповідати на
запитання лише «так» або «ні». Протягом 60 секунд учасник від команди має
вгадати те, що зображено на малюнку.

**Comment by irynaa-semchuk** [comment]
Мені подобається конкурс, думаю учасникам буде цікаво)
Може вже є ідеї для зображень для хлопців і дівчат?

**Comment by nsavchuk41** [comment]
[https://lh3.googleusercontent.com/proxy/Q5Fx_U1j_WxdodOmWsSREG6x47dzd6SqGWkxXTa5BWGd5peideu5HJMTNAcinplF1P5mv0wYn0lbry9B0x-sIhSsy6zTjMJ87BvojXImIECTwcfYchBTxTArynYPwRtHc0U](url) 
давайте дівчата будуть відгадувати дану картинку

**Comment by irynaa-semchuk** [comment]
Хлопці можуть відгадувати цю картинку
![hdd](https://user-images.githubusercontent.com/48826465/111874654-d701f580-899e-11eb-897f-7781670fd539.jpg)

**Comment by Galiv** [comment]
Супер! Дякую за картинки, йду створювати ПР
